# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# ! opt-in for individual modules (e.g., aws, docker, gcloud, nodejs, python)
# standalone format to get os glyph on ps1 line,
# prompt character below
format = """
$username$hostname$directory$git_branch$git_commit$cmd_duration
$character
"""

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[ ❱❱](104)[❱](blue)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
error_symbol = '[ ❱❱](104)[❱](red)'

# ---

[os]
format = '[$symbol](bold 104) '
disabled = false

# ---y

# Shows the username
[username]
style_user = 'bold 104'
style_root = 'black bold'
format = ' [\[$user~]($style)'
disabled = false
show_always = true

# Shows the hostname
[hostname]
ssh_only = false
format = '[$hostname](bold 104) '
disabled = false

# Shows current directory
[directory]
truncation_length = 3
truncation_symbol = '…/'
home_symbol = '~'
read_only_style = ' bold 140'
read_only = ' '

format = '[$path](bold 140)[$read_only\]]($read_only_style) '

# Shows current git branch
[git_branch]
symbol = ''
format = '[\($symbol $branch\)]($style) '
truncation_length = 15
truncation_symbol = '…/'
style = 'bold 072'

# Shows current git status
# [git_status]
# format = '[$all_status$ahead_behind\)]($style) '
# style = 'bold 072'
# conflicted = '⚐'
# up_to_date = '☝'
# untracked = ' '
# ahead = '⇡${count}'
# diverged = '⇕⇡${ahead_count}⇣${behind_count}'
# behind = '⇣${count}'
# stashed = ' '
# modified = ' '
# staged = '[++\($count\)](072)'
# renamed = '✎ '
# deleted = ' '
